name: ESX Template Server (HU)
description: Magyar ESX szerver sablon Achim-Sommer alapján
tasks:
  - action: download_github
    src: Achim-Sommer/FiveM-ESX-Template-Server
    ref: main
    dest: ./resources/[esx]/esx-template
